platform :ios, '10.0'
inhibit_all_warnings!
 
workspace 'AgoraEducation.xcworkspace'
install! 'cocoapods', :deterministic_uuids => false, :warn_for_unused_master_specs_repo => false
 
target 'AgoraEducation' do
  use_frameworks!
  
  # third libs
  pod "CocoaLumberjack",   '3.6.1'
  pod 'AliyunOSSiOS',      '2.10.8'
  pod 'SSZipArchive',      '2.4.2'
  pod 'SwifterSwift',      '5.2.0'
  pod 'SDWebImage',        '5.12.0'
  pod 'Masonry',           '1.1.0'
  pod 'Armin',             '1.1.1'
  
  # agora libs
  pod 'AgoraRtcEngine_Special_iOS',  '3.7.2.134'
  pod 'AgoraMediaPlayer_iOS',        '1.3.0'
  pod 'Agora_Chat_iOS',              '1.0.6'
  pod 'AgoraRtm_iOS',                '1.5.1'
  pod 'Whiteboard', 		     '2.16.103'
 
  # open source libs
  pod 'AgoraClassroomSDK_iOS', '2.8.101'
  pod 'AgoraEduUI',            '2.8.101'
  
  pod 'AgoraProctorSDK',       '1.0.1'
  pod 'AgoraProctorUI',        '1.0.0'
  
  pod 'AgoraWidgets',          '2.8.103'
  
  # close source libs
  pod 'AgoraUIBaseViews',      '2.8.101'
  pod 'AgoraEduCore', 	       '2.8.103'
  pod 'AgoraWidget',           '2.8.0'

  # post install, no signing for pods bundle, after xcode 14
  post_install do |installer|
    ## Fix for XCode 12.5
    find_and_replace("Pods/FBRetainCycleDetector/FBRetainCycleDetector/Layout/Classes/FBClassStrongLayout.mm",
                     "layoutCache[currentClass] = ivars;", "layoutCache[(id<NSCopying>)currentClass] = ivars;")
    
    # no signing for pods bundle
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
